# Generated by Django 5.0 on 2023-12-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoria', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='')),
                ('Color', models.CharField(max_length=20)),
                ('Largo', models.CharField(max_length=20)),
                ('Circunsferencia', models.CharField(max_length=20)),
            ],
        ),
    ]
